### ISSUE TITLE
Tools  Disappearing

### ISSUE THREAD

**Issue by N4ttNatt** [Ning1253/Pickaxe-Stats#7]
Hi, I downloaded the latest release, loaded and every tool/sword I hold gets deleted instantly, im still trying to find a way around this bug but i got nothing, just letting ya know!

**Comment by PeterPgit** [comment]
Hey, I've updated this datapack and am just waiting for Ning to accept the pull request. You can download the updated version off of my fork though, in case you're eager to try it out!

**Comment by Ning1253** [comment]
Done!! The datapack is now up to date
