### ISSUE TITLE
Collaborator

### ISSUE THREAD

**Issue by PeterPgit** [Ning1253/Pickaxe-Stats#8]
Hello, I'm the guy who has been helping to create the datapack with you. I was just wondering if I could be added as a collaborator so that you 1) Don't have to keep manually accepting pull requests and 2) Because I've made some edits to the pack personalized to me, so I don't want some of the edits to be pushed to the main pack.

Thanks!

**Comment by Ning1253** [comment]
Of course!! Once again sorry for having been away for so long, I'm back to working on the pack now

**Comment by PeterPgit** [comment]
Not a problem at all. I saw that you were looking into implementing a selection mechanism: I've got (what seems like) a working version of that, though I want to do a little more testing first. It's nearly there though, and then I'll send it over to you to test out and mess around with

**Comment by Ning1253** [comment]
Cool, send it over when you can! I'll be working on making tools bind to one player for now.
